version: "3"
services: 
  mongodb_graphql_server:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"

volumes: 
  mongo-data:
    driver: local
